In [2]:
#How to declare numpy array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#How to declare 2d array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(type(arr2))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [10]:
arr = np.array([1,2,3,4,5])
# slicing of single-dimentional array
print(arr[0])   # it prints first element
print(arr[-1])   # it prints last element
print(arr[0:])  # it prints 0 to last index
print(arr[:])   # it prints all the items
print(arr[:5])   # it prints first element to 5th

1
5
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [17]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
# slicing of 2d array
print(arr2[0,0:3])   # it prints 0 to 2 index of sub-array of 0th index of main array
print(arr2[0:2])     # it prints 0 to 1st index of main array
print(arr2[0:2,0:2])   # it prints 0th to 1st index of first two sub array
print(arr2[0:2,0:3])   # it prints 0th to 2nd index of both sub array, we can not print different indexes
print(arr2[0,0:])
print(arr2[1,0:2])

[1 2 3]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2]
 [6 7]]
[[1 2 3]
 [6 7 8]]
[1 2 3 4 5]
[6 7]


In [10]:
import numpy as np
arr = np.array([1.0,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
# inspecting an array
print(np.shape(arr))
print(np.shape(arr2))   # it returns (row,column)
print(np.size(arr))
print(np.size(arr2))  # it returns number of elements present in array
print("Length of arr2: ",len(arr2))   # it retuens number of sub array present in array
print(np.ndim(arr))
print(np.ndim(arr2))   # it returns number of dimention
print(arr.dtype)
print(arr2.dtype)
print(arr2.astype(float))  # it is used for type casting

(5,)
(3, 5)
5
15
Length of arr2:  3
1
2
float64
int64
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


In [25]:
# mathematical operations
arr = [1,2,3,4,5,6]
arr2 = [7,8,5,6,9,4]
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("arr + arr2: ",arr+arr2)
print("Addition: ",np.add(arr,arr2))
print("Subtraction: ",np.subtract(arr,arr2))
print("Multiplication: ", np.multiply(arr,arr2))
print("Division: ", np.divide(arr, arr2))
powerArr = np.power(arr,2)
powerArr3 = np.power(arr3,2)
print("Power of arr: ", np.power(arr,4))
print("Power of arr2: ",np.power(arr2,3))
print("Power of arr3: ",np.power(arr3,2))
print("Square Root of powerArr: ",np.sqrt(powerArr))

arr + arr2:  [1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 9, 4]
Addition:  [ 8 10  8 10 14 10]
Subtraction:  [-6 -6 -2 -2 -4  2]
Multiplication:  [ 7 16 15 24 45 24]
Division:  [0.14285714 0.25       0.6        0.66666667 0.55555556 1.5       ]
Power of arr:  [   1   16   81  256  625 1296]
Power of arr2:  [343 512 125 216 729  64]
Power of arr3:  [[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]
Square Root of powerArr:  [1. 2. 3. 4. 5. 6.]
